name: Ruff

on: [pull_request, push]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - uses: chartboost/ruff-action@v1
        with:
          src: "./collect_data"
